import Head from 'next/head'
import Card from '../components/RegisterMask/Card'
import OrderTest from '../components/OrderTest'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card />
      <div style={{ display: 'flex', justifyContent: 'center', marginTop: 30 }}>
        <OrderTest />
      </div>
    </div>
  )
}
