import Head from 'next/head'
import Card from '../components/RegisterMask/Card'
import OrderTest from '../components/OrderTest'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card />
      <div className='flex justify-center t-[30px]'>
        <OrderTest />
      </div>
    </div>
  )
}
